changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - feature
        - semver-minor
    - title: Fixes and maintenance
      labels:
        - bug
        - fix
        - dependencies
        - semver-patch
    - title: Other changes
      labels:
        - '*'
  change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
  exclude:
    labels:
      - skip-changelog
