---
# Per environment values which override defaults in hmpps-electronic-monitoring-data-insights-ui/values.yaml

generic-service:
  ingress:
    host: electronic-monitoring-data-insights-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://electronic-monitoring-data-insights-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EMDI_API_URL: 'https://electronic-monitoring-data-insights-api.hmpps.service.justice.gov.uk'
    EMDI_API_TIMEOUT_RESPONSE: "15000"
    EMDI_API_TIMEOUT_DEADLINE: "20000"
    AUDIT_ENABLED: "false"
    COMPONENT_API_URL: "https://probation-frontend-components.hmpps.service.justice.gov.uk"
    MPOP_URL: "https://manage-people-on-probation.hmpps.service.justice.gov.uk"
    ENABLE_HEATMAP: "false"
    ENABLE_PING_CARD_NAVIGATION: "false"
generic-prometheus-alerts:
  alertSeverity: hmpps-electronic-monitoring-data-insights-prod
